### ISSUE TITLE
Certain projectile and player collisions are not always detected

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#274] opened 2023-12-28 07:36 UTC
- Skills like takedown+flesh hook and other unnamed abilities that share similar functionality will pass through players when going at too high of a velocity
- Probably should make a method in a helper class that uses custom collision logic to detect things for these abilities

**Comment by braulio-dev** [comment] 2023-12-29 23:31
Duplicate of #231

**Comment by braulio-dev** [comment] 2023-12-29 23:32
Duplicate of #231

**Closed by braulio-dev** 2023-12-29 23:31 UTC
Labels: duplicate
